# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clother.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Clother(object):
    def setupUi(self, Clother):
        Clother.setObjectName("Clother")
        Clother.resize(621, 369)
        self.centralwidget = QtWidgets.QWidget(Clother)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 151, 184))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 40, 141, 184))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_2.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_2.addWidget(self.checkBox_14)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(410, 40, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_15 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_3.addWidget(self.checkBox_16)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 10, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 10, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(410, 10, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 240, 121, 41))
        self.pushButton.setObjectName("pushButton")
        Clother.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Clother)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 26))
        self.menubar.setObjectName("menubar")
        Clother.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Clother)
        self.statusbar.setObjectName("statusbar")
        Clother.setStatusBar(self.statusbar)

        self.retranslateUi(Clother)
        QtCore.QMetaObject.connectSlotsByName(Clother)

    def retranslateUi(self, Clother):
        _translate = QtCore.QCoreApplication.translate
        Clother.setWindowTitle(_translate("Clother", "MainWindow"))
        self.checkBox.setText(_translate("Clother", "Head"))
        self.checkBox_2.setText(_translate("Clother", "Shoulders"))
        self.checkBox_3.setText(_translate("Clother", "Chest"))
        self.checkBox_4.setText(_translate("Clother", "Arms"))
        self.checkBox_5.setText(_translate("Clother", "Belt"))
        self.checkBox_6.setText(_translate("Clother", "Pants"))
        self.checkBox_7.setText(_translate("Clother", "Boots"))
        self.checkBox_8.setText(_translate("Clother", "Head"))
        self.checkBox_9.setText(_translate("Clother", "Shoulders"))
        self.checkBox_10.setText(_translate("Clother", "Chest"))
        self.checkBox_11.setText(_translate("Clother", "Arms"))
        self.checkBox_12.setText(_translate("Clother", "Belt"))
        self.checkBox_13.setText(_translate("Clother", "Pants"))
        self.checkBox_14.setText(_translate("Clother", "Boots"))
        self.checkBox_15.setText(_translate("Clother", "Epic"))
        self.checkBox_16.setText(_translate("Clother", "Legendary"))
        self.lineEdit.setText(_translate("Clother", "Light"))
        self.lineEdit_2.setText(_translate("Clother", "Medium"))
        self.lineEdit_3.setText(_translate("Clother", "Quality"))
        self.pushButton.setText(_translate("Clother", "Make a gold!"))


